// ──────────────────────────────────────────────────────────────────
//  AnthonyTheSabakumono — Test Registry
//  To add a new test: copy one object below and change the fields.
//  No other file needs editing.
// ──────────────────────────────────────────────────────────────────

const TESTS = [
  {
    id:         "EEE-01",
    title:      "ЭЕШ English Mock Test",
    subtitle:   "Жинхэнэ мэт мэдрэмж",
    href:       "EEE-01/index.html",
    category:   "ЭЕШ",
    lang:       "EN",
    questions:  40,
    minutes:    80,
    difficulty: 4,          // 1–5
    sections:   ["Grammar", "Vocabulary", "Reading"],
    score:      "200–800",
    desc:       "Англи хэл Элсэлтийн ерөнхий шалгалтыг дуурайлган бүтээсэн mock test. Оноо нь 200–800 хуваарь дээр тооцогдоно.",
    featured:   true,
    new:        false,
  },
  {
     id:         "CEFR-01",
     title:      "Англи хэл түвшин тогтоох шалгалт",
     subtitle:   "Маш хурдан түвшингээ мэдэх боломж",
     href:       "CEFR-01/index.html",
     category:   "CEFR",
     lang:       "EN",
     questions:  20,
     minutes:    40,
     difficulty: 3,
     sections:   ["Grammar", "Vocabulary", 'Reading'],
     score:      "A1–C2",
     desc:       "20хон асуултаар түвшингээ мэдэх боломжтой сорил.",
     featured:   true,
     new:        false,
   },
  {
     id:         "JLPT-01",
     title:      "Япон хэл түвшин тогтоох шалгалт",
     subtitle:   "Маш хурдан түвшингээ мэдэх боломж",
     href:       "JLPT-01/index.html",
     category:   "JLPT",
     lang:       "JP",
     questions:  20,
     minutes:    40,
     difficulty: 3,
     sections:   ["Grammar", "Vocabulary", 'Reading'],
     score:      "N5-N1",
     desc:       "20хон асуултаар түвшингээ мэдэх боломжтой сорил.",
     featured:   true,
     new:        false,
   },
  {
     id:         "PERS-01",
     title:      "Зан чанарын тест",
     subtitle:   "Маш хурдан өөрийн зан чанарыг мэдэх боломж",
     href:       "PERS-01/index.html",
     category:   "PERSONALITY",
     lang:       "MN",
     questions:  20,
     minutes:    40,
     difficulty: 0,
     sections:   ["Асуулт"],
     score:      "Extrovert-Introvert",
     desc:       "20хон асуултаар өөрийн зан чанарыг мэдэх боломжтой сорил.",
     featured:   true,
     new:        true,
   },
];
